[project]
name = "fee-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "AAAkater", email = "aaakater@qq.com" }]
requires-python = ">=3.12"
dependencies = ["numpy>=2.2.6"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
